#ifndef ADD_ENDGAME_SCALEFACTOR_1_VS_0
#define ADD_ENDGAME_SCALEFACTOR_1_VS_0 \
\
add<KPK>("KPK");\
add<KPK>("KAPK");\
add<KPK>("KBPK");\
add<KPK>("KAPKA");\
add<KPK>("KAPKAA");\
add<KPK>("KAPKB");\
add<KPK>("KAPKBB");\
add<KPK>("KBPKA");\
add<KPK>("KBPKB");\
add<KPK>("KAAPK");\
add<KPK>("KABPK");\
add<KPK>("KBBPK");\
add<KPK>("KAAPKA");\
add<KPK>("KAAPKB");\
add<KPK>("KABPKA");\
add<KPK>("KABPKB");\
add<KPK>("KBBPKA");\
add<KPK>("KBBPKB");\
add<KPK>("KAAPKAA");\
add<KPK>("KAAPKAB");\
add<KPK>("KAAPKBB");\
add<KPK>("KABPKAA");\
add<KPK>("KABPKAB");\
add<KPK>("KABPKBB");\
add<KPK>("KBBPKAA");\
add<KPK>("KBBPKAB");\
add<KPK>("KBBPKBB");\
add<KPK>("KAABPK");\
add<KPK>("KABBPK");\
add<KPK>("KAABPKA");\
add<KPK>("KAABPKB");\
add<KPK>("KABBPKA");\
add<KPK>("KABBPKB");\
add<KPK>("KAABPKAA");\
add<KPK>("KAABPKAB");\
add<KPK>("KAABPKBB");\
add<KPK>("KABBPKAA");\
add<KPK>("KABBPKAB");\
add<KPK>("KABBPKBB");\
add<KPK>("KAABPKAAB");\
add<KPK>("KAABPKABB");\
add<KPK>("KABBPKAAB");\
add<KPK>("KABBPKABB");\
add<KPK>("KAABBPK");\
add<KPK>("KAABBPKA");\
add<KPK>("KAABBPKB");\
add<KPK>("KAABBPKAA");\
add<KPK>("KAABBPKAB");\
add<KPK>("KAABBPKBB");\
add<KPK>("KAABBPKAAB");\
add<KPK>("KAABBPKABB");\
add<KPK>("KAABBPKAABB");\
\
add<KNK>("KNK");\
add<KNK>("KNKA");\
add<KNK>("KNKB");\
add<KNK>("KNKAA");\
add<KNK>("KNKAB");\
add<KNK>("KNKBB");\
add<KNK>("KNKAAB");\
add<KNK>("KNKABB");\
add<KNK>("KANK");\
add<KNK>("KBNK");\
add<KNK>("KANKA");\
add<KNK>("KANKB");\
add<KNK>("KBNKA");\
add<KNK>("KBNKB");\
add<KNK>("KANKAA");\
add<KNK>("KANKAB");\
add<KNK>("KANKBB");\
add<KNK>("KBNKAA");\
add<KNK>("KBNKAB");\
add<KNK>("KBNKBB");\
add<KNK>("KANKAAB");\
add<KNK>("KANKABB");\
add<KNK>("KBNKAAB");\
add<KNK>("KBNKABB");\
add<KNK>("KANKAABB");\
add<KNK>("KBNKAABB");\
add<KNK>("KAANK");\
add<KNK>("KABNK");\
add<KNK>("KBBNK");\
add<KNK>("KAANKA");\
add<KNK>("KAANKB");\
add<KNK>("KABNKA");\
add<KNK>("KABNKB");\
add<KNK>("KBBNKA");\
add<KNK>("KBBNKB");\
add<KNK>("KAANKAA");\
add<KNK>("KAANKAB");\
add<KNK>("KAANKBB");\
add<KNK>("KABNKAA");\
add<KNK>("KABNKAB");\
add<KNK>("KABNKBB");\
add<KNK>("KBBNKAA");\
add<KNK>("KBBNKAB");\
add<KNK>("KBBNKBB");\
add<KNK>("KAANKAAB");\
add<KNK>("KAANKABB");\
add<KNK>("KABNKAAB");\
add<KNK>("KABNKABB");\
add<KNK>("KBBNKAAB");\
add<KNK>("KBBNKABB");\
add<KNK>("KAANKAABB");\
add<KNK>("KABNKAABB");\
add<KNK>("KBBNKAABB");\
add<KNK>("KAABNK");\
add<KNK>("KABBNK");\
add<KNK>("KAABNKA");\
add<KNK>("KAABNKB");\
add<KNK>("KABBNKA");\
add<KNK>("KABBNKB");\
add<KNK>("KAABNKAA");\
add<KNK>("KAABNKAB");\
add<KNK>("KAABNKBB");\
add<KNK>("KABBNKAA");\
add<KNK>("KABBNKAB");\
add<KNK>("KABBNKBB");\
add<KNK>("KAABNKAAB");\
add<KNK>("KAABNKABB");\
add<KNK>("KABBNKAAB");\
add<KNK>("KABBNKABB");\
add<KNK>("KAABNKAABB");\
add<KNK>("KABBNKAABB");\
add<KNK>("KAABBNK");\
add<KNK>("KAABBNKA");\
add<KNK>("KAABBNKB");\
add<KNK>("KAABBNKAA");\
add<KNK>("KAABBNKAB");\
add<KNK>("KAABBNKBB");\
add<KNK>("KAABBNKAAB");\
add<KNK>("KAABBNKABB");\
add<KNK>("KAABBNKAABB");\
\
add<KCK>("KCK");\
add<KCK>("KCKA");\
add<KCK>("KCKB");\
add<KCK>("KCKAA");\
add<KCK>("KCKAB");\
add<KCK>("KCKBB");\
add<KCK>("KCKAAB");\
add<KCK>("KCKABB");\
add<KCK>("KACK");\
add<KCK>("KBCK");\
add<KCK>("KACKA");\
add<KCK>("KACKB");\
add<KCK>("KBCKA");\
add<KCK>("KBCKB");\
add<KCK>("KACKAA");\
add<KCK>("KACKAB");\
add<KCK>("KACKBB");\
add<KCK>("KBCKAA");\
add<KCK>("KBCKAB");\
add<KCK>("KBCKBB");\
add<KCK>("KACKAAB");\
add<KCK>("KACKABB");\
add<KCK>("KBCKAAB");\
add<KCK>("KBCKABB");\
add<KCK>("KACKAABB");\
add<KCK>("KBCKAABB");\
add<KCK>("KAACK");\
add<KCK>("KABCK");\
add<KCK>("KBBCK");\
add<KCK>("KAACKA");\
add<KCK>("KAACKB");\
add<KCK>("KABCKA");\
add<KCK>("KABCKB");\
add<KCK>("KBBCKA");\
add<KCK>("KBBCKB");\
add<KCK>("KAACKAA");\
add<KCK>("KAACKAB");\
add<KCK>("KAACKBB");\
add<KCK>("KABCKAA");\
add<KCK>("KABCKAB");\
add<KCK>("KABCKBB");\
add<KCK>("KBBCKAA");\
add<KCK>("KBBCKAB");\
add<KCK>("KBBCKBB");\
add<KCK>("KAACKAAB");\
add<KCK>("KAACKABB");\
add<KCK>("KABCKAAB");\
add<KCK>("KABCKABB");\
add<KCK>("KBBCKAAB");\
add<KCK>("KBBCKABB");\
add<KCK>("KAACKAABB");\
add<KCK>("KABCKAABB");\
add<KCK>("KBBCKAABB");\
add<KCK>("KAABCK");\
add<KCK>("KABBCK");\
add<KCK>("KAABCKA");\
add<KCK>("KAABCKB");\
add<KCK>("KABBCKA");\
add<KCK>("KABBCKB");\
add<KCK>("KAABCKAA");\
add<KCK>("KAABCKAB");\
add<KCK>("KAABCKBB");\
add<KCK>("KABBCKAA");\
add<KCK>("KABBCKAB");\
add<KCK>("KABBCKBB");\
add<KCK>("KAABCKAAB");\
add<KCK>("KAABCKABB");\
add<KCK>("KABBCKAAB");\
add<KCK>("KABBCKABB");\
add<KCK>("KAABCKAABB");\
add<KCK>("KABBCKAABB");\
add<KCK>("KAABBCK");\
add<KCK>("KAABBCKA");\
add<KCK>("KAABBCKB");\
add<KCK>("KAABBCKAA");\
add<KCK>("KAABBCKAB");\
add<KCK>("KAABBCKBB");\
add<KCK>("KAABBCKAAB");\
add<KCK>("KAABBCKABB");\
add<KCK>("KAABBCKAABB");\
\
add<KRK>("KRK");\
add<KRK>("KRKA");\
add<KRK>("KRKB");\
add<KRK>("KRKAA");\
add<KRK>("KRKAB");\
add<KRK>("KRKBB");\
add<KRK>("KRKAAB");\
add<KRK>("KRKABB");\
add<KRK>("KRKAABB");\
add<KRK>("KARK");\
add<KRK>("KBRK");\
add<KRK>("KARKA");\
add<KRK>("KARKB");\
add<KRK>("KBRKA");\
add<KRK>("KBRKB");\
add<KRK>("KARKAA");\
add<KRK>("KARKAB");\
add<KRK>("KARKBB");\
add<KRK>("KBRKAA");\
add<KRK>("KBRKAB");\
add<KRK>("KBRKBB");\
add<KRK>("KARKAAB");\
add<KRK>("KARKABB");\
add<KRK>("KBRKAAB");\
add<KRK>("KBRKABB");\
add<KRK>("KARKAABB");\
add<KRK>("KBRKAABB");\
add<KRK>("KAARK");\
add<KRK>("KABRK");\
add<KRK>("KBBRK");\
add<KRK>("KAARKA");\
add<KRK>("KAARKB");\
add<KRK>("KABRKA");\
add<KRK>("KABRKB");\
add<KRK>("KBBRKA");\
add<KRK>("KBBRKB");\
add<KRK>("KAARKAA");\
add<KRK>("KAARKAB");\
add<KRK>("KAARKBB");\
add<KRK>("KABRKAA");\
add<KRK>("KABRKAB");\
add<KRK>("KABRKBB");\
add<KRK>("KBBRKAA");\
add<KRK>("KBBRKAB");\
add<KRK>("KBBRKBB");\
add<KRK>("KAARKAAB");\
add<KRK>("KAARKABB");\
add<KRK>("KABRKAAB");\
add<KRK>("KABRKABB");\
add<KRK>("KBBRKAAB");\
add<KRK>("KBBRKABB");\
add<KRK>("KAARKAABB");\
add<KRK>("KABRKAABB");\
add<KRK>("KBBRKAABB");\
add<KRK>("KAABRK");\
add<KRK>("KABBRK");\
add<KRK>("KAABRKA");\
add<KRK>("KAABRKB");\
add<KRK>("KABBRKA");\
add<KRK>("KABBRKB");\
add<KRK>("KAABRKAA");\
add<KRK>("KAABRKAB");\
add<KRK>("KAABRKBB");\
add<KRK>("KABBRKAA");\
add<KRK>("KABBRKAB");\
add<KRK>("KABBRKBB");\
add<KRK>("KAABRKAAB");\
add<KRK>("KAABRKABB");\
add<KRK>("KABBRKAAB");\
add<KRK>("KABBRKABB");\
add<KRK>("KAABRKAABB");\
add<KRK>("KABBRKAABB");\
add<KRK>("KAABBRK");\
add<KRK>("KAABBRKA");\
add<KRK>("KAABBRKB");\
add<KRK>("KAABBRKAA");\
add<KRK>("KAABBRKAB");\
add<KRK>("KAABBRKBB");\
add<KRK>("KAABBRKAAB");\
add<KRK>("KAABBRKABB");\
add<KRK>("KAABBRKAABB");\

#endif
